name: Manual Kernel Build for Lancelin

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y bc bison flex libssl-dev build-essential git wget curl unzip cpio

    - name: Clone Kernel Source
      run: |
        git clone https://github.com/adhit21/minati_kernel_lancelin.git
        cd minati_kernel_lancelin
        git submodule update --init --recursive

    - name: Build Kernel
      run: |
        cd minati_kernel_lancelin
        export ARCH=arm64
        export CROSS_COMPILE=aarch64-linux-gnu-
        make O=out lancelin_defconfig
        make -j$(nproc) O=out

    - name: Upload Kernel Image
      uses: actions/upload-artifact@v4
      with:
        name: Kernel-Image
        path: minati_kernel_lancelin/out/arch/arm64/boot/Image.gz-dtb
